Update "What You Will Need" Section
spring-guides/gs-spring-cloud-loadbalancer pull request #8
Opened 2021-05-20 15:12 UTC by ilkou

Use `The raw.githubusercontent.com` domain to serve unprocessed versions of 2 files, and eventually adding the 2nd option (To **skip the basics**) to the "What You Will Need" Section

2021-05-20 15:12 UTC, pivotal-cla commented
@ilkou Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-cloud-loadbalancer&pullRequestId=8)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-cloud-loadbalancer&pullRequestId=8) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-05-20 15:14 UTC, pivotal-cla commented
@ilkou Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-cloud-loadbalancer&pullRequestId=8)!

2023-10-19 18:28 UTC, Buzzardo requested changes

2023-10-19 18:28 UTC, Buzzardo commented on README.adoc
> +== What You Need
We don't want to lose the `About 15 minutes` line. That's a marketing point for the guides.

2026-02-06 19:09 UTC, snicoll commented
@ilkou it was heading in the right direction. I've harmonized this section in https://github.com/spring-guides/gs-spring-cloud-loadbalancer/commit/89401ee1ed4f94f35e2bfc9267bb9efd0a619e20. Thanks for the PR in any case!

2026-02-06 19:09 UTC, closed without merging